src/DecFP.jl
This fixes just the one deprecation warning with dictionaries on `Julia v0.5`.
=> fix dictionary deprecation warning

README.md
"and hence is mainly for developers at this point"
What package isn't for "developers"..?
Just seemed old, for 0.4-dev.
[ci skip]
=> Just works [on 0.5]?

src/DecFP.jl, test/runtests.jl
The addition of `trunc` will help with the formatted printing issue #26.
=> Add trunc and Integer methods for floor, ceil, convert

src/DecFP.jl, test/runtests.jl
Fixes Issue #26.  Implements %f %F %e %E %g %G.  Doesn't implement %a/%A.
I also added the Dec*(x::AbstractString) constructor to simplify writing the tests.
=> Fix printf formatting

deps/build.jl
Also, I don't think Compat is needed in the build file anymore.
=> fix deprecation of Compat.KERNEL

REQUIRE, src/DecFP.jl
I will work on a better `show`, but for now eliminate the `ismatch` deprecation warning.
=> ismatch deprecation

REQUIRE, src/DecFP.jl, test/runtests.jl
Reimplement `show` without using `@sprintf`.  The motivation for doing this is to `show` values without rounding.
```
julia> maxintfloat(Dec128) - 1
9.999999999999999999999999999999999e33
```
A side effect of the reimplementation is some recently reported display issues also go away
```
julia> realmin(d64"3.4")
1.0e-398
julia> realmin(Dec64)
1.0e-398
julia> parse(Dec128, "56123")
56123.0
julia> parse(Dec128, "561234")
561234.0
```
Please keep issue #59 open since I still need to address this in `@sprintf`
cc @ScottPJones
=> Reimplement show

src/DecFP.jl, test/runtests.jl
Fixes #59 
```
julia> @sprintf("%e", realmin(Dec64))
"1.000000e-398"
julia> realmax(Dec64)
9.999999999999999e384
julia> @sprintf("%e", realmax(Dec64))
"1.000000e+385"
```
I uncommented the definitions for `exponent` and `ldexp` and renamed to `exponent10` and `ldexp10` to avoid confusion with Base `exponent` and `ldexp`.  I like the name `scale10` better than `ldexp10`.  Do you have a preference on this?  I am currently using these within `DecFP.jl` but not exporting them.  I also defined `tostring` to wrap the library's `to_string`.  I welcome a better name for this.
=> Round without overflow (Fix #59)

src/DecFP.jl
Fixes compatibility with Julia 1.1 as commented https://github.com/JuliaLang/julia/issues/30374#issuecomment-446788652 and https://github.com/JuliaLang/julia/pull/30373#issuecomment-446801542, due to recent changes in Julia printf internals.
cc @JeffBezanson
=> fix digits buffer for Julia 1.1

.travis.yml, REQUIRE, appveyor.yml, src/DecFP.jl, test/runtests.jl
The main advantage is that it enables usage of `setrounding(f, T, mode)` style.
=> use MPFR-style rounding enum

.gitignore, Project.toml, REQUIRE, src/DecFP.jl
`Base.Printf` was removed with https://github.com/JuliaLang/julia/pull/33313.
Julia nightly now requires Project.toml https://github.com/JuliaLang/Pkg.jl/pull/1356.
Fixes https://github.com/JuliaMath/DecFP.jl/issues/98
=> Printf reorg / add Project.toml

Project.toml
Would be great with a merge + tag here since that fixes this package on Julia master. x-ref https://github.com/JuliaRegistries/Registrator.jl/issues/249
=> Set version to 0.4.9 and correct Julia compat.

src/DecFP.jl, test/runtests.jl
Correct `floatmin()` to conform to the Julia definition:
Return the smallest positive normal number representable by the floating-point type T.
Fixes #82.
=> Correct floatmin()

Project.toml, src/DecFP.jl, test/runtests.jl
Fixes #100 `lgamma` gets a deprecation warning from SpecialFunctions.
```
julia> using DecFP
julia> using SpecialFunctions
julia> lgamma(d64"4.0")
┌ Warning: `lgamma(x::Real)` is deprecated, use `(logabsgamma(x))[1]` instead.
│   caller = top-level scope at REPL[3]:1
└ @ Core REPL[3]:1
1.791759469228055
julia> logabsgamma(d64"4.0")
(1.791759469228055, 1)
julia> logabsgamma(d64"4.0")[1]
1.791759469228055
```
=> Add logabsgamma

src/DecFP.jl
Since we now require Julia 1.3, remove old `printf` compatibility.
=> Remove old printf compat

src/DecFP.jl, test/runtests.jl
When I write a full set of tests for `hash()`, they will test `decompose()` more completely.  Fixes #108
=> Comparison with Rational

src/DecFP.jl, test/runtests.jl
Initial implementation failed with
```
julia> d64"1" / d64"6" == 1//6
true
```
=> Update Rational comparison

src/DecFP.jl, test/runtests.jl
=> Implement tryparse()

test/runtests.jl
Closes #97.  `hash()` was fixed with PRs #114, #115, #121.  This PR just adds tests.
=> hash() tests

.drone.jsonnet, .drone.yml, .github/workflows/CompatHelper.yml, .github/workflows/TagBot.yml, .travis.yml, appveyor.yml
* add CompatHelper
* reduce frequency of TagBot to once per day
* add scripts to run CI on ARM architectures with Drone CI (see https://discourse.julialang.org/t/testing-on-arm-with-drone-ci/25871, this needs to be activated [here](https://cloud.drone.io/JuliaMath/DecFP.jl/settings) by someone with admin rights in this repository)
* add FreeBSD to Travis
* run Travis only on master, instead of all branches
* cache artifacts on Travis and AppVeyor (see https://discourse.julialang.org/t/recommendation-cache-julia-artifacts-in-ci-services/35484)
=> Some improvements to CI

src/DecFP.jl, test/runtests.jl
Some of this is needed for the rewrite of #129 but it is generally useful so I kept going until it passed all the obvious tests.
```
julia> Int128(Dec32(5))
5
julia> Dec64(Int128(10000000000000000000000))
1.0e22
```
=> Int128 support

Project.toml, src/DecFP.jl, test/runtests.jl
Implements `rand()` but not `randn()` or `randexp()`.  We should implement the Ziggurat Method for `randn()` and `randexp()`.  Most of the tests including `hist()` were copied directly from stdlib/Random/test.  Partially addresses issue #80.
=> Implement rand()

src/DecFP.jl, test/runtests.jl
I opted to have this return `Integers` instead of floating point values.  Most uses of this function are probably looking for integers and this avoids the inefficiency of converting an integer to floating point which the user immediately converts back to integer.  One consequence of returning integers is that this function throws a `DomainError` for `Inf` or `NaN` inputs.  The user would need to check for and handle these values anyway; this just encourages the check before calling `sigexp`.
```
julia> sigexp(d64"-1.25")
(-1, 125, -2)
julia> sigexp(d64"1")
(1, 1, 0)
julia> sigexp(d64"1.0")
(1, 10, -1)
```
Fixes #130 
cc @quinnj
=> Export sigexp

src/DecFP.jl
Change return type of `logabsgamma` to conform with SpecialFunctions v1.6.  Closes #145.
=> Update return type for logabsgamma

.drone.jsonnet, .drone.yml
32-bit systems are now tested with GitHub actions, and the armv7l job for Julia
v1.7 is stalling for unrelated reasons.
Also, run Drone CI only on `master` branch, to avoid duplicate jobs in pull
requests.
=> Remove ARM 32-bit jobs from drone

src/DecFP.jl, test/runtests.jl
Component part construction performs some redundant conversions on constants.
The conversions are more costly than they look, as the decimal to integer path range checks against type ranges on the integer types, which in turn performs conversions of these to the decimal type. For `Dec128/UInt128` this is particularly bad as the integer to decimal conversion falls back to conversion via strings.
Fixed by precomputing integer constants.
Simple example benchmark in the form of
```Julia
@btime T($(Ref(123))[], $(Ref(-8))[])
```
| T | before | after |
| --- | --- | --- |
| Dec32 | 10.701 ns (0 allocations: 0 bytes) | 4.200 ns (0 allocations: 0 bytes) |
| Dec64 | 11.912 ns (0 allocations: 0 bytes)  | 3.810 ns (0 allocations: 0 bytes) |
| Dec128 | 394.069 ns (6 allocations: 288 bytes) | 6.510 ns …
=> Optimize component part construction

src/DecFP.jl, test/runtests.jl
Fixes #131, based on suggestion by @jmkuhn.
=> fix integer comparisons

src/DecFP.jl, test/runtests.jl
For Irrational comparisions ==, <=, >= we are using Base functions:
==(x::Real, y::AbstractIrrational) = false
<=(x::AbstractFloat, y::AbstractIrrational) = x < y
etc
Fixes #122
=> Fix Irrational and BigFloat comparisons

.drone.yml, .github/workflows/CI.yml, Project.toml, test/runtests.jl
Test that issue #134 is fixed by DecFP_jll v2.0.3+1
The Julia requirement of v1.6 is set by the limit in DecFP_jll ([PR](https://github.com/JuliaPackaging/Yggdrasil/pull/3860/files)).
Codecov shouldn't decrease since tests were the only thing added.
Closes #134.
=> Test rounding when parsing strings

.github/workflows/CI.yml
In particular, this is necessary for Codecov reporting to work
=> Update CI.yml to use latest actions

src/DecFP.jl
The Julia library defines
convert(::Type{T}, x::T)      where {T<:Number} = x
convert(::Type{T}, x::Number) where {T<:Number} = T(x)::T
So the canonical way to provide additional conversions between `Number`
subtypes is by providing constructors.
We thus remove resp. replace almost all `convert` methods in DecFP.
=> Reduce method invalidations

src/DecFP.jl, test/runtests.jl
Closes #153.
Only a relatively small slowdown (5–30% for `Dec64`) for basic arithmetic, so a task-local rounding mode doesn't seem to be a huge concern.  OLD CODE:
```jl
julia> @btime sum($(rand(Dec64, 1000)));
45.614 μs (0 allocations: 0 bytes)
julia> @btime sum(n -> d64"0.9999"^n, 1:1000);
933.454 μs (0 allocations: 0 bytes)
```
NEW CODE:
```jl
julia> @btime sum($(rand(Dec64, 1000)));
60.292 μs (0 allocations: 0 bytes)
julia> @btime sum(n -> d64"0.9999"^n, 1:1000);
961.635 μs (0 allocations: 0 bytes)
```
(The first benchmark should be the worst case, because it is only calling `+`, which is relatively cheap.)
=> Thread safety: per-task state rather than per-thread

src/DecFP.jl
To deal with the warnings introduced by https://github.com/JuliaLang/julia/pull/57311.
=> Explicitely qualify extended constructors
